#!/usr/bin/env bash
# KP5 LATENT-RL FINETUNE — WRIST-WRITING SPECIALIZATION.
#
# PPO over the distilled MUSE-Kp KP5 *latent* (frozen decoder = motor prior), specialized
# on the in-air letter-writing task: the right wrist tracks letter-shaped trajectories in
# front of the robot, the policy is free to locomote (mask pinned right-wrist-only).
#
# Differences vs run_muse_kp_latent_rl.sh:
#   - Task: MUSE-Kp-LatentRL-Kp5-Writing-...  (KP5, canonical; KP6 is legacy)
#   - Motion: the 2000-word synthetic writing pool (npz_synth_pool), NOT SONIC train.
#   - Env forces start_from_beginning=True (synth clips are valid only at frame 0) and
#     pins the mask to right-wrist-only — both baked into the env cfg, no flags needed.
#   - Warmstart: the kp5_latent_distill checkpoint (the policy that makes the demo videos).
#
# Reward / termination / adapter come from the env + runner cfg (already match the agreed
# spec: world-frame visible-POI pos+vel reward + penalty bundle; fall-class terminations;
# residual adapter). Tune reward weights via Hydra overrides (e.g.
# env.rewards.poi_pos.weight=...) — see the env cfg LatentRLRewardsCfg.
#
# Required env vars (or fall back to defaults below):
#   ENCODER_DECODER_WARMSTART   the kp5_latent_distill .pt to finetune
#
# Common overrides:
#   CUDA_VISIBLE_DEVICES, MOTION_DIR, NUM_ENVS, RUN_NAME, RESUME_CHECKPOINT,
#   ADAPTER (residual default | lora | full_ft), INIT_LATENT_STD, CRITIC_WARMUP_ITRS,
#   LEARNING_RATE, LORA_RANK/LORA_ALPHA/LORA_TARGETS (ADAPTER=lora)
#
# Example:
#   ENCODER_DECODER_WARMSTART=logs/rsl_rl/g1_flat_muse_kp_latent_distillation/2026-05-19_13-19-35_muse_kp5_latent_distill/model_14000.pt \
#   bash run/train/MUSE/run_muse_kp_latent_rl_writing.sh

set -euo pipefail

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"

# The distilled KP5 policy to finetune (the one that makes the writing demo videos).
ENCODER_DECODER_WARMSTART="${ENCODER_DECODER_WARMSTART:-logs/rsl_rl/g1_flat_muse_kp_latent_distillation/2026-05-19_13-19-35_muse_kp5_latent_distill/model_14000.pt}"

# The 2000-word writing pool (generated by scripts/synth_cli.py pool-generate).
MOTION_DIR="${MOTION_DIR:-/home/lsn/Datasets/SONIC_npzs/g1/npz_synth_pool}"
NUM_ENVS="${NUM_ENVS:-2048}"
RUN_NAME="${RUN_NAME:-muse_kp5_latentrl_writing}"
RESUME_CHECKPOINT="${RESUME_CHECKPOINT:-}"
ADAPTER="${ADAPTER:-residual}"

# Count GPUs in CUDA_VISIBLE_DEVICES for nproc_per_node.
IFS=',' read -r -a _gpu_arr <<<"$CUDA_VISIBLE_DEVICES"
NPROC="${#_gpu_arr[@]}"

EXTRA_ARGS=()
if [[ -n "${RESUME_CHECKPOINT:-}" ]]; then
    EXTRA_ARGS+=(--resume_student_checkpoint "$RESUME_CHECKPOINT")
fi
if [[ -n "${ADAPTER:-}" ]]; then
    EXTRA_ARGS+=(agent.policy.adapter="$ADAPTER")
fi
if [[ -n "${LORA_RANK:-}" ]]; then
    EXTRA_ARGS+=(agent.policy.lora_rank="$LORA_RANK")
fi
if [[ -n "${LORA_ALPHA:-}" ]]; then
    EXTRA_ARGS+=(agent.policy.lora_alpha="$LORA_ALPHA")
fi
if [[ -n "${LORA_TARGETS:-}" ]]; then
    EXTRA_ARGS+=(agent.policy.lora_targets="$LORA_TARGETS")
fi
if [[ -n "${INIT_LATENT_STD:-}" ]]; then
    EXTRA_ARGS+=(agent.policy.init_latent_std="$INIT_LATENT_STD")
fi
if [[ -n "${CRITIC_WARMUP_ITRS:-}" ]]; then
    EXTRA_ARGS+=(agent.algorithm.critic_warmup_itrs="$CRITIC_WARMUP_ITRS")
fi
if [[ -n "${LEARNING_RATE:-}" ]]; then
    EXTRA_ARGS+=(agent.algorithm.learning_rate="$LEARNING_RATE")
fi
if [[ -n "${ENCODER_DECODER_WARMSTART:-}" ]]; then
    EXTRA_ARGS+=(--encoder_decoder_warmstart "$ENCODER_DECODER_WARMSTART")
fi

HYDRA_FULL_ERROR=1 torchrun --standalone --nnodes=1 --nproc_per_node="$NPROC" scripts/rsl_rl/train.py \
    --task=MUSE-Kp-LatentRL-Kp5-Writing-General-Tracking-Flat-G1-v0 \
    --distributed \
    --num_envs="$NUM_ENVS" \
    --motion "$MOTION_DIR" \
    --headless \
    --logger wandb \
    --log_project_name MUSE_LatentRL \
    --run_name "$RUN_NAME" \
    "${EXTRA_ARGS[@]}"

# ENCODER_DECODER_WARMSTART=logs/rsl_rl/g1_flat_muse_kp_latent_distillation/2026-05-19_13-19-35_muse_kp5_latent_distill/model_14000.pt bash run/train/MUSE/run_muse_kp_latent_rl_writing.sh
